cmd_drivers/misc/mediatek/masp/asf/auth/sec_wrapper.o := aarch64-linux-android-gcc -Wp,-MD,drivers/misc/mediatek/masp/asf/auth/.sec_wrapper.o.d  -nostdinc -isystem /home/adeveloper79/toolchains/UBERTC/aarch64-linux-android-5.3/bin/../lib/gcc/aarch64-linux-android/5.3.1/include -I/home/adeveloper79/Android7K3NoTE/arch/arm64/include -Iarch/arm64/include/generated  -Iinclude -I/home/adeveloper79/Android7K3NoTE/arch/arm64/include/uapi -Iarch/arm64/include/generated/uapi -I/home/adeveloper79/Android7K3NoTE/include/uapi -Iinclude/generated/uapi -include /home/adeveloper79/Android7K3NoTE/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Wno-format-security -fno-delete-null-pointer-checks -mtune=cortex-a53 -ffast-math -march=armv8-a -std=gnu89 -O2 -ffast-math -mgeneral-regs-only -fno-pic -mtune=cortex-a53 -march=armv8-a -O2 -ftree-vectorize -Wframe-larger-than=1400 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -I/home/adeveloper79/Android7K3NoTE/drivers/misc/mediatek/mach/mt6752/include -Idrivers/misc/mediatek/masp/asf/asf_inc -Idrivers/misc/mediatek/masp/asf/asf_inc -Idrivers/misc/mediatek/masp/asf/asf_inc -Idrivers/misc/mediatek/masp/module    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(sec_wrapper)"  -D"KBUILD_MODNAME=KBUILD_STR(sec)" -c -o drivers/misc/mediatek/masp/asf/auth/sec_wrapper.o drivers/misc/mediatek/masp/asf/auth/sec_wrapper.c

source_drivers/misc/mediatek/masp/asf/auth/sec_wrapper.o := drivers/misc/mediatek/masp/asf/auth/sec_wrapper.c

deps_drivers/misc/mediatek/masp/asf/auth/sec_wrapper.o := \

drivers/misc/mediatek/masp/asf/auth/sec_wrapper.o: $(deps_drivers/misc/mediatek/masp/asf/auth/sec_wrapper.o)

$(deps_drivers/misc/mediatek/masp/asf/auth/sec_wrapper.o):
