cmd_drivers/misc/mediatek/fmradio/dummy.o := /home/nikolay/aosp/prebuild/aarch64-elf-5.3.0-Linux-x86_64/bin/aarch64-elf-gcc -Wp,-MD,drivers/misc/mediatek/fmradio/.dummy.o.d  -nostdinc -isystem /home/nikolay/aosp/prebuild/aarch64-elf-5.3.0-Linux-x86_64/bin/../lib/gcc/aarch64-elf/5.3.0/include -I/home/nikolay/aosp/Android7K3NoTE/arch/arm64/include -Iarch/arm64/include/generated  -Iinclude -I/home/nikolay/aosp/Android7K3NoTE/arch/arm64/include/uapi -Iarch/arm64/include/generated/uapi -I/home/nikolay/aosp/Android7K3NoTE/include/uapi -Iinclude/generated/uapi -include /home/nikolay/aosp/Android7K3NoTE/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Wno-format-security -fno-delete-null-pointer-checks -mtune=cortex-a53 -march=armv8-a -std=gnu89 -O2 -mgeneral-regs-only -fno-pic -mtune=cortex-a53 -march=armv8-a -O2 -ftree-vectorize -Wframe-larger-than=1400 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -I/home/nikolay/aosp/Android7K3NoTE/drivers/misc/mediatek/mach/mt6752/include -D MTK_WCN_REMOVE_KERNEL_MODULE -I/home/nikolay/aosp/Android7K3NoTE/drivers/misc/mediatek/mach/mt6752/include -DWMT_PLAT_ALPS=1 -DMT6627_FM -DMT6625_FM -Idrivers/misc/mediatek/fmradio/inc -Idrivers/misc/mediatek/fmradio/mt6627/inc -Idrivers/misc/mediatek/fmradio/../connectivity/conn_soc/common/include -Idrivers/misc/mediatek/fmradio/../connectivity/conn_soc/common/linux/include -Idrivers/misc/mediatek/fmradio/../connectivity/common_detect    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(dummy)"  -D"KBUILD_MODNAME=KBUILD_STR(dummy)" -c -o drivers/misc/mediatek/fmradio/dummy.o drivers/misc/mediatek/fmradio/dummy.c

source_drivers/misc/mediatek/fmradio/dummy.o := drivers/misc/mediatek/fmradio/dummy.c

deps_drivers/misc/mediatek/fmradio/dummy.o := \

drivers/misc/mediatek/fmradio/dummy.o: $(deps_drivers/misc/mediatek/fmradio/dummy.o)

$(deps_drivers/misc/mediatek/fmradio/dummy.o):
